config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy,:index]
  resources :icons, only: [:new, :create]

  resources :pictures do
    collection do
      post :confirm
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/icon.rb
class Icon < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :image, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  # validates :content, presence: true, length: { maximum:2200 }
  validates :image, presence: true

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  validates :password, presence: true, length: { minimum: 6 }

  has_many :favorites, dependent: :destroy
  has_many :pictures,  through: :favorites
  has_one :icon

# メールアドレスをDBに保存する直前に小文字にして、同じアドレスが登録されることを防ぐ
   before_save { email.downcase! }
   has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    # まず現在current_userのidを取得する
    # その人が沖にいるしているpictureを取得する
    @favorites = current_user.favorites

  end


  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path
  end

  def destroy
    favorite = current_user.favorites.find_by(picture_id: params[:id]).destroy
    redirect_to pictures_path
  end
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  def new
    @user_id = current_user.id
    @icon = Icon.new
  end

  def create

    @icon = Icon.new(params_icon)
    @icon.user_id = current_user.id

    @icon.save
     redirect_to users_path
  end

  def params_icon
    params.require(:icon).permit(:image)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show,:edit,:update,:destroy]
  before_action :force_login, only: [:new,:edit,:index]

  def index
    # 一覧画面に表示させるために全てのレコードを取得

    @pictures = Picture.all

  end

  def show
    # 詳細画面でfavoriteするかしないかを渡すインスタンス

    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    # 投稿画面のformに渡すためのインスタンス変数
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create

    @picture = Picture.new(picture_params)
    # userとpictureテーブルが結びついているので、user_idを取得しなければエラーとなってしまうので下記の記述いる
    @picture.user_id = current_user.id
    @picture.image.retrieve_from_cache! params[:cache][:image] if params[:cache][:image].present?

   if @picture.save
     PictureMailer.picture_mail(@picture).deliver
     redirect_to pictures_path
   else
    render 'new'
   end

  end

  def edit
    # まず編集したいコンテンツのidを取得する必要がある
  end

  def update

    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "Content has been succesfully edited"
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
      redirect_to pictures_path, notice: "Content has been succesfully deleted"
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id

    render :new if @picture.invalid?

  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end


  def picture_params
    params.require(:picture).permit(:content,:image)
  end

  def force_login
    if !logged_in?
      redirect_to new_session_path , notice: "ログインしてください"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    user = User.find_by(email: params[:session][:email].downcase)
    # authenticateメソッドは引数にパスワードを渡すことで、認証の成否を判定する
    if user &&  user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      # sessionコントローラーからもUserモデルにアクセスすることができる（紐づいていないコントローラーとモデル）
      redirect_to pictures_path
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

 def destroy
   session.delete(:user_id)
  flash[:notice] = 'ログアウトしました'
  redirect_to new_session_path

 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit,:update]

  def new
    # form_withに渡すインスタンス変数を作成
    @user = User.new
  end

  def index

    # 全ての投稿の中から現在ログインしているユーザーの投稿を取り出す
    @pictures = Picture.where(user_id: current_user)

  end

  def create
    # パラメーターで値を取得して、オブジェクト作成
    @user = User.new(user_params)

    # pictures コントローラーの一覧画面へリダイレクトさせる
    if @user.save
      redirect_to pictures_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update

    if @user.update(user_params)
      redirect_to users_path notice: "プロフィール情報を編集しました"
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
      #!はfalseを返す current_userは中に何か入っているか？という意味
    !current_user.nil?  
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class="whole_profile_and_favorite">
  <div class="profile">

  <% if current_user.icon.present? %>
   <span><%= image_tag current_user.icon.image.url,  class:"profile_icon" %></span>
  <% end %>

   <span><%= current_user.name %></span>
   <p><%= link_to "プロフィールを編集", edit_user_path(current_user.id) %></p>
  </div>
  
<div class="my_pictures">
  <div class="picture_or_favorite">
  <span><%= link_to "投稿一覧", users_path %></span>
  <span><%= link_to "お気に入り一覧", favorites_path %></span>
  </div>

  <div>
    <% @favorites.each do |favorite| %>
    <%= image_tag  favorite.picture.image.url, :size => "250" %>
    <% end %>
  </div>
</div>
</div>

app/views/icons/new.html.erb
<div class="form_parent">
<%= form_with(model: @icon, local: true) do |form| %>
  <div class="form_child">
    <p>プロフィール画像</p>
    <%= form.file_field :image%>
    <%= form.hidden_field :image_cashe %>
  </div>
  <%= form.submit %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %><link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid navbar-static-top">
      <i class="fa fa-instagram fa-3x" aria-hidden="true"></i>
      <p class="logo" href="#"> Instagram</p>

      <% if logged_in? %>
      <ul class="top_menu">

        <li class="list_right"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
        <li class="list_right"><%= link_to "Profile", users_path(current_user.id) %> /</li>

        <li class="list_right"><%= link_to "新規投稿", new_picture_path %></li>
        <li class="list_right"><%= link_to "Home", pictures_path %> /</li>

        <% else %>
        <li class="list_right"><%= link_to "Sign up", new_user_path %></li>
        <li class="list_right"><%= link_to "Login", new_session_path %></li>
      </ul>
      <% end %>



      <!-- <ul class="top_menu"> -->
      <!-- <% if logged_in? %> -->

      <!-- <% end %> -->
     <!-- </ul> -->
    </div>
  </nav>


  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>


    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<div class="form_parent">
<%= form_with(model: @picture, local: true,url: choose_new_or_edit ) do |form| %>
  <div class="form_child">
    <%= form.file_field :image%>
    <%= form.hidden_field :image_cashe %>
    <%= form.text_area :content, placeholder: "Content" %>
  </div>
  <%= form.submit %>
<% end %>
</div>

app/views/pictures/confirm.html.erb
<div class="form_parent">
<div class="form_child">
  <h4>以下の内容で投稿する</h4>
  <%= form_with(model: @picture, local: true) do |form| %>
      <%= form.hidden_field :content %>
    <div>
      <p><%= image_tag @picture.image , :width => "50%" %></p>
      <%= hidden_field_tag :"cache[image]", @picture.image.cache_name %>
      <p>Content:<%= @picture.content %></p>
    </div>
    <%= form.submit "Create post" %>
  <% end %>

  <!-- 戻るボタンはform_forで作成することで、パラメーターを渡すことができる -->
  <%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
    <%= form.hidden_field :content %>
    <%= form.submit "Back" , name: 'back' %>
  <% end %>
</div>
<div>

app/views/pictures/edit.html.erb
<%= render 'form' %>

app/views/pictures/index.html.erb
<div class="article">
<% @pictures.each do |picture| %>
  <!-- ユーザー情報
  <tr>
    <td><%= picture.content  %></td>
  </tr> -->
 <div class="insta_whole_content">
  <div class="insta_creater">
    <span><%= image_tag picture.user.icon.image.url, :class => "menu_icon" if picture.user.icon.present? %></span>
    <span><%= picture.user.name  %></span>
  </div>
  <div class="insta_image">
    <%= image_tag picture.image.url, :width => "100%" %>
  </div>

  <div class="insta_content">
    <p><%= picture.content  %></p>
    <!-- <span><%= link_to "詳細を見る", picture_path(picture.id)%></span> -->
    <% if picture.user == current_user %>
    <span><%= link_to "編集する", edit_picture_path(picture.id)%></span>
    <span><%= link_to "削除する", picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？'} %></span>
    <% end %>


    <% @favorite = current_user.favorites.find_by(picture_id: picture.id) %>
    <% unless picture.user == current_user %>
     <% if @favorite.present? %>
      <span><%= link_to 'お気に入り解除する', favorite_path(picture.id), method: :delete %></span>
     <% else %>
      <span><%= link_to 'お気に入りする', favorites_path(picture_id: picture.id),  method: :post %></span>
     <% end %>
    <% end %>
  </div>
 </div>
<% end %>
</div>

app/views/pictures/new.html.erb
<%= render 'form' %>

app/views/pictures/show.html.erb
<h2>詳細ページ</h2>
<p><%= image_tag @picture.image %></p>
<p><%= @picture.content %></p>

<% unless @picture.user == current_user %>
 <% if @favorite.present? %>
   <%= link_to 'お気に入り解除する', favorite_path(@picture.id), method: :delete %>
 <% else %>
   <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id),  method: :post %>
    
 <% end %>
<% end %>

app/views/users/_user.html.erb
<div class="whole_form">

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<div class="common_form">
  <h1>Sign up</h1>
  <%= form_with(model: @user, local: true) do |f| %>
   <div class="each_form">
    <%= f.text_field :name, :placeholder => "Name" %>
  </div>

  <div class="each_form">
    <%= f.email_field :email, :placeholder => "Email" %>
  </div>

  <div class="each_form">
    <%= f.password_field :password, :placeholder => "Password" %>
  </div>

  <div class="each_form">

    <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %>
  </div>

  <div class="each_form">
    <%= f.submit "Sign up" %>
  </div>

 <% end %>
</div>
</div>

app/views/users/edit.html.erb
<div class="whole_form">

<div class="common_form">
  <h1>プロフィール編集</h1>
  <p><%= link_to "プロフィール写真を設定", new_icon_path %></p>
  <%= form_with(model: @user, local: true) do |f| %>
   <div class="each_form">
    <%= f.text_field :name, :placeholder => "Name" %>
  </div>

  <div class="each_form">
    <%= f.email_field :email, :placeholder => "Email" %>
  </div>

  <div class="each_form">
    <%= f.password_field :password, :placeholder => "Password" %>
  </div>

  <div class="each_form">

    <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %>
  </div>

  <div class="each_form">
    <%= f.submit "Update profile" %>
  </div>

 <% end %>
</div>
</div>

app/views/users/index.html.erb
<div class="whole_profile_and_favorite">
  <div class="profile">

  <% if current_user.icon.present? %>
   <span><%= image_tag current_user.icon.image.url,  class:"profile_icon" %></span>
  <% end %>

   <span><%= current_user.name %></span>
   <p><%= link_to "プロフィールを編集", edit_user_path(current_user.id) %></p>
  </div>

  <div class="my_pictures">
    <div class="picture_or_favorite">
    <span><%= link_to "投稿一覧"%></span>
    <span><%= link_to "お気に入り一覧", favorites_path %></span>
    </div>

    <div>
      <% @pictures.each do |picture| %>
      <%= image_tag picture.image.url, :size => "250" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'user' %>
<!-- <div class="whole_form">

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<div class="common_form">
  <h1>Sign up</h1>
  <%= form_with(model: @user, local: true) do |f| %>
   <div class="each_form">
    <%= f.text_field :name, :placeholder => "Name" %>
  </div>

  <div class="each_form">
    <%= f.email_field :email, :placeholder => "Email" %>
  </div>

  <div class="each_form">
    <%= f.password_field :password, :placeholder => "Password" %>
  </div>

  <div class="each_form">

    <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %>
  </div>

  <div class="each_form">
    <%= f.submit "Sign up" %>
  </div>

 <% end %>
</div>
</div> -->

app/views/users/show.html.erb
<h1>プロフィール詳細</h1>
<%= current_user.name %>
<div>
<span><%= link_to "投稿一覧"%></span>
<span><%= link_to "お気に入り一覧" %></span>
</div>